INSERT INTO MPA (mpa_id, NAME) VALUES (1, 'G');
INSERT INTO MPA (mpa_id, NAME) VALUES (2, 'PG');
INSERT INTO MPA (mpa_id, NAME) VALUES (3, 'PG-13');
INSERT INTO MPA (mpa_id, NAME) VALUES (4, 'R');
INSERT INTO MPA (mpa_id, NAME) VALUES (5, 'NC-17');