DELETE FROM mpa;
INSERT INTO MPA (mpa_id, NAME) VALUES (1, 'G');
INSERT INTO MPA (mpa_id, NAME) VALUES (2, 'PG');
INSERT INTO MPA (mpa_id, NAME) VALUES (3, 'PG-13');
INSERT INTO MPA (mpa_id, NAME) VALUES (4, 'R');
INSERT INTO MPA (mpa_id, NAME) VALUES (5, 'NC-17');

INSERT INTO GENRES (GENRE_ID, NAME) VALUES (1, 'Комедия');
INSERT INTO GENRES (GENRE_ID, NAME) VALUES (2, 'Драма');
INSERT INTO GENRES (GENRE_ID, NAME) VALUES (3, 'Мультфильм');
INSERT INTO GENRES (GENRE_ID, NAME) VALUES (4, 'Триллер');
INSERT INTO GENRES (GENRE_ID, NAME) VALUES (5, 'Документальный');
INSERT INTO GENRES (GENRE_ID, NAME) VALUES (6, 'Боевик');

